---
server:
  port: 9999
---
spring:
  profiles: DEV
  application:
    name: gateway-client
eureka:
 client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.profiles.active}:${spring.application.instance_id:${random.value}}
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'
   
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
    beans:
      enabled: false
  endpoint:
    shutdown:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000  
